name: sales_force_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"  # Ensure compatibility with null safety

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.40.0
  cupertino_icons: ^1.0.8
  syncfusion_flutter_charts: ^28.1.41

flutter:
  assets:
    - assets/icons8-progress-64.png
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
